"""Generate PTDataStatistics' bundled site rules from PTDepilerMp JSON files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from pprint import pformat


SOURCE_REPOSITORY = "https://github.com/zyt0339/MoviePilot-Plugins"
SOURCE_COMMIT = "7480ca57a96254680c47bed2b1f74bacb6018f42"


def load_rules(source: Path) -> tuple[dict, ...]:
    """Load production rule files deterministically without dropping fields."""

    rules: list[dict] = []
    for path in sorted(source.glob("*.json"), key=lambda item: item.name.casefold()):
        if path.name == "1demo.json":
            continue
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict) or not str(value.get("name") or "").strip():
            raise ValueError(f"Invalid site rule: {path}")
        if not isinstance(value.get("levels"), list):
            raise ValueError(f"Invalid level list: {path}")
        # 文件名是上游规则仓库用于定位站点的稳定标识。保留它，供 MP
        # 展示名、域名与中文规则名不一致时参与匹配。
        value["source_key"] = path.stem
        rules.append(value)
    return tuple(rules)


def render(rules: tuple[dict, ...]) -> str:
    """Render a self-contained Python data module with source provenance."""

    header = f'''"""Bundled PTDepilerMp site-level rules.

Generated by ``tools/generate_ptdatastatistics_site_rules.py`` from:
{SOURCE_REPOSITORY}/tree/{SOURCE_COMMIT}/plugins.v2/ptdepilermp/site_rules

The source data is GPL-3.0 licensed. See ``site_rules.LICENSE``.
Do not edit this generated file by hand.
"""

from __future__ import annotations

from typing import Any, Final

SOURCE_REPOSITORY: Final = {SOURCE_REPOSITORY!r}
SOURCE_COMMIT: Final = {SOURCE_COMMIT!r}

SITE_LEVEL_RULES: Final[tuple[dict[str, Any], ...]] = '''
    return header + pformat(rules, width=120, sort_dicts=False) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    rules = load_rules(args.source)
    args.output.write_text(render(rules), encoding="utf-8", newline="\n")
    print(f"generated {len(rules)} rules: {args.output}")


if __name__ == "__main__":
    main()
